Topic
Saika3569/ASTRO-Camp-T101- pull request #3
Opened 2021-02-19 08:46 UTC by Saika3569

測試

2021-02-19 09:03 UTC, shes50103 requested changes

2021-02-19 09:03 UTC, shes50103 commented on app/views/tasks/_form.html.erb
> +<% end %>
最後一行，要留個空白行
vscode 可以設定自動補空白行

2021-02-19 09:03 UTC, shes50103 commented on app/views/tasks/edit.html.erb
>  <%= render 'form',task: @task %>
```ruby
render 'form',task: @task
```

, 後面記得加空格

```ruby
render 'form', task: @task
```

2021-02-19 09:03 UTC, shes50103 commented on config/application.rb
> +    end
這些設定是要做什麼的？

2021-02-19 09:03 UTC, shes50103 commented on spec/controllers/tasks_controller_spec.rb
> +      @task = create(:task)
試試看用 rspec 的 (let)[https://relishapp.com/rspec/rspec-core/v/3-10/docs/helper-methods/let-and-let] 重構

```ruby
let(:task){ create(:task) }
```

2021-02-19 09:03 UTC, shes50103 commented on spec/models/task_spec.rb
> +  end
試試看用 [shoulda-matchers](https://github.com/thoughtbot/shoulda-matchers) 重構這段

應該可以重構成這樣
```ruby
  describe 'validations' do
     it { should validate_presence_of(: user_id) }
     it { should validate_presence_of(: content) }
     it { should validate_presence_of(: title) }
  end
```

2021-02-19 09:03 UTC, shes50103 commented on spec/models/task_spec.rb
> +  end
這段也可以用 shoudla-matcher

```ruby
  describe 'validations' do
    it { should validate_uniqueness_of(:title).scoped_to(:user_id) }
  end
```

2021-02-19 09:03 UTC, shes50103 commented on Gemfile
> +  gem "rails-controller-testing"
建議 gem 後面版本號要寫完整
```
 gem "factory_bot_rails", '~>6.1.0'
 gem "rails-controller-testing", '~>1.0.5'
```

2021-02-19 09:14 UTC, Saika3569 commented on config/application.rb
> +    end
設定在rails g 時不要自動產生spec檔案，
 controller_specs: true是要解決如果用rspec:controller時變成request的spec的bug

2021-02-19 10:31 UTC, shes50103 commented on spec/controllers/tasks_controller_spec.rb
> +      get :show, params: {id: task }
這邊是不是要這樣寫才對？
```ruby
get :show, params: {id: task.id }
```

2021-02-19 10:31 UTC, shes50103 commented on spec/controllers/tasks_controller_spec.rb
> +    let(:task){ create(:task) }
這麼多地方用到 `let(:task){ create(:task) }` 可以把它往外移
就不用每個 describe 都寫一次
let 有 lazy load 特性
沒用到的測試就不會載入

2021-02-19 10:42 UTC, Saika3569 commented
get :show, params: {id: task.id }

2021-02-22 01:44 UTC, shes50103 approved these changes

2021-02-22 06:22 UTC, merged